In [1]:
import pandas as pd

# Load the dataset
train_df = pd.read_csv("C:/Users/LENOVO/Desktop/Project/hackathon/train.csv")  
test_df = pd.read_csv("C:/Users/LENOVO/Desktop/Project/hackathon/test.csv")   

# Check the first few rows of the train dataset
print(train_df.head())

# Get general information about the dataset
print(train_df.info())

# Check for missing values
print(train_df.isnull().sum())

# Get the description of the data
train_df.describe()

   id      Name  Gender   Age           City Working Professional or Student  \
0   0  Aaradhya  Female  49.0       Ludhiana            Working Professional
1   1     Vivan    Male  26.0       Varanasi            Working Professional
2   2    Yuvraj    Male  33.0  Visakhapatnam                         Student
3   3    Yuvraj    Male  22.0         Mumbai            Working Professional
4   4      Rhea  Female  30.0         Kanpur            Working Professional

         Profession  Academic Pressure  Work Pressure  CGPA  \
0              Chef                NaN            5.0   NaN
1           Teacher                NaN            4.0   NaN
2               NaN                5.0            NaN  8.97
3           Teacher                NaN            5.0   NaN
4  Business Analyst                NaN            1.0   NaN

   Study Satisfaction  Job Satisfaction     Sleep Duration Dietary Habits  \
0                 NaN               2.0  More than 8 hours        Healthy
1                 NaN               3.0  Less than 5 hours      Unhealthy
2                 2.0               NaN          5-6 hours        Healthy
3                 NaN               1.0  Less than 5 hours       Moderate
4                 NaN               1.0          5-6 hours      Unhealthy

    Degree Have you ever had suicidal thoughts ?  Work/Study Hours  \
0      BHM                                    No               1.0
1      LLB                                   Yes               7.0
2  B.Pharm                                   Yes               3.0
3      BBA                                   Yes              10.0
4      BBA                                   Yes               9.0

   Financial Stress Family History of Mental Illness  Depression
0               2.0                               No           0
1               3.0                               No           1
2               1.0                               No           1
3               1.0                              Yes           1
4               4.0                              Yes           0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140700 entries, 0 to 140699
Data columns (total 20 columns):
 #   Column                                 Non-Null Count   Dtype
---  ------                                 --------------   -----
 0   id                                     140700 non-null  int64
 1   Name                                   140700 non-null  object
 2   Gender                                 140700 non-null  object
 3   Age                                    140700 non-null  float64
 4   City                                   140700 non-null  object
 5   Working Professional or Student        140700 non-null  object
 6   Profession                             104070 non-null  object
 7   Academic Pressure                      27897 non-null   float64
 8   Work Pressure                          112782 non-null  float64
 9   CGPA                                   27898 non-null   float64
 10  Study Satisfaction                     27897 non-null   float64
 11  Job Satisfaction                       112790 non-null  float64
 12  Sleep Duration                         140700 non-null  object
 13  Dietary Habits                         140696 non-null  object
 14  Degree                                 140698 non-null  object
 15  Have you ever had suicidal thoughts ?  140700 non-null  object
 16  Work/Study Hours                       140700 non-null  float64
 17  Financial Stress                       140696 non-null  float64
 18  Family History of Mental Illness       140700 non-null  object
 19  Depression                             140700 non-null  int64
dtypes: float64(8), int64(2), object(10)
memory usage: 21.5+ MB
None
id                                            0
Name                                          0
Gender                                        0
Age                                           0
City                                          0
Working Professional or Student               0
Profession                                36630
Academic Pressure                        112803
Work Pressure                             27918
CGPA                                     112802
Study Satisfaction                       112803
Job Satisfaction                          27910
Sleep Duration                                0
Dietary Habits                                4
Degree                                        2
Have you ever had suicidal thoughts ?         0
Work/Study Hours                              0
Financial Stress                              4
Family History of Mental Illness              0
Depression                                    0
dtype: int64

,id,Age,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Work/Study Hours,Financial Stress,Depression
count,140700.000000,140700.000000,27897.000000,112782.000000,27898.000000,27897.000000,112790.000000,140700.000000,140696.000000,140700.000000
mean,70349.500000,40.388621,3.142273,2.998998,7.658636,2.944940,2.974404,6.252679,2.988983,0.181713
std,40616.735775,12.384099,1.380457,1.405771,1.464466,1.360197,1.416078,3.853615,1.413633,0.385609
min,0.000000,18.000000,1.000000,1.000000,5.030000,1.000000,1.000000,0.000000,1.000000,0.000000
25%,35174.750000,29.000000,2.000000,2.000000,6.290000,2.000000,2.000000,3.000000,2.000000,0.000000
50%,70349.500000,42.000000,3.000000,3.000000,7.770000,3.000000,3.000000,6.000000,3.000000,0.000000
75%,105524.250000,51.000000,4.000000,4.000000,8.920000,4.000000,4.000000,10.000000,4.000000,0.000000
max,140699.000000,60.000000,5.000000,5.000000,10.000000,5.000000,5.000000,12.000000,5.000000,1.000000

In [2]:
# Identify columns that are categorical (non-numeric)
categorical_cols = train_df.select_dtypes(include=['object']).columns
print("Categorical columns:", categorical_cols)

# You can either drop the columns or encode them into numeric values
#  Convert categorical columns into dummy variables (one-hot encoding)
train_df = pd.get_dummies(train_df, columns=categorical_cols, drop_first=True)

# Now, check the dataset again
print(train_df.head())

# Fill missing values with median or mode for numerical or categorical columns
train_df.fillna(train_df.median(), inplace=True)

Categorical columns: Index(['Name', 'Gender', 'City', 'Working Professional or Student',
       'Profession', 'Sleep Duration', 'Dietary Habits', 'Degree',
       'Have you ever had suicidal thoughts ?',
       'Family History of Mental Illness'],
      dtype='object')
   id   Age  Academic Pressure  Work Pressure  CGPA  Study Satisfaction  \
0   0  49.0                NaN            5.0   NaN                 NaN
1   1  26.0                NaN            4.0   NaN                 NaN
2   2  33.0                5.0            NaN  8.97                 2.0
3   3  22.0                NaN            5.0   NaN                 NaN
4   4  30.0                NaN            1.0   NaN                 NaN

   Job Satisfaction  Work/Study Hours  Financial Stress  Depression  ...  \
0               2.0               1.0               2.0           0  ...
1               3.0               7.0               3.0           1  ...
2               NaN               3.0               1.0           1  ...
3               1.0              10.0               1.0           1  ...
4               1.0               9.0               4.0           0  ...

   Degree_S.Pharm  Degree_S.Tech  Degree_UX/UI Designer  Degree_Unite  \
0           False          False                  False         False
1           False          False                  False         False
2           False          False                  False         False
3           False          False                  False         False
4           False          False                  False         False

   Degree_Veda  Degree_Vivaan  Degree_Vrinda  Degree_Working Professional  \
0        False          False          False                        False
1        False          False          False                        False
2        False          False          False                        False
3        False          False          False                        False
4        False          False          False                        False

   Have you ever had suicidal thoughts ?_Yes  \
0                                      False
1                                       True
2                                       True
3                                       True
4                                       True

   Family History of Mental Illness_Yes
0                                 False
1                                 False
2                                 False
3                                  True
4                                  True

[5 rows x 766 columns]

In [3]:
# Identify categorical columns in test dataset
categorical_cols_test = test_df.select_dtypes(include=['object']).columns
print("Categorical columns in test data:", categorical_cols_test)

# Apply one-hot encoding to test_df (same as train_df)
test_df = pd.get_dummies(test_df, columns=categorical_cols_test, drop_first=True)

# Fill missing values in test_df with the median
test_df.fillna(test_df.median(), inplace=True)

# Check the processed test dataset
print(test_df.head())

Categorical columns in test data: Index(['Name', 'Gender', 'City', 'Working Professional or Student',
       'Profession', 'Sleep Duration', 'Dietary Habits', 'Degree',
       'Have you ever had suicidal thoughts ?',
       'Family History of Mental Illness'],
      dtype='object')
       id   Age  Academic Pressure  Work Pressure  CGPA  Study Satisfaction  \
0  140700  53.0                3.0            2.0  7.80                 3.0
1  140701  58.0                3.0            2.0  7.80                 3.0
2  140702  53.0                3.0            4.0  7.80                 3.0
3  140703  23.0                5.0            3.0  6.84                 1.0
4  140704  47.0                3.0            5.0  7.80                 3.0

   Job Satisfaction  Work/Study Hours  Financial Stress  Name_AHM  ...  \
0               5.0               9.0               3.0     False  ...
1               4.0               6.0               4.0     False  ...
2               1.0              12.0               4.0     False  ...
3               3.0              10.0               4.0     False  ...
4               5.0               3.0               4.0     False  ...

   Degree_PhD  Degree_Pune  Degree_RCA  Degree_Rupak  Degree_S.Pharm  \
0       False        False       False         False           False
1       False        False       False         False           False
2       False        False       False         False           False
3       False        False       False         False           False
4       False        False       False         False           False

   Degree_Travel Consultant  Degree_Vibha  Degree_Vrinda  \
0                     False         False          False
1                     False         False          False
2                     False         False          False
3                     False         False          False
4                     False         False          False

   Have you ever had suicidal thoughts ?_Yes  \
0                                      False
1                                      False
2                                       True
3                                       True
4                                       True

   Family History of Mental Illness_Yes
0                                  True
1                                 False
2                                 False
3                                 False
4                                 False

[5 rows x 653 columns]

In [4]:
# Handle missing values (e.g., impute with median or drop)
train_df.fillna(train_df.median(), inplace=True)  
test_df.fillna(train_df.median(),inplace=True)

In [9]:
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

# Define features (X) and target (y)
X = train_df.drop('Depression', axis=1) 
y = train_df['Depression']  

# Split the data into training and validation sets
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the XGBoost model
xgb_model = XGBClassifier(n_estimators=200, learning_rate=0.05, max_depth=6, random_state=42)

# Train the model
xgb_model.fit(X_train, y_train)

# Predict on the validation set
y_pred = xgb_model.predict(X_valid)

# Evaluate the model
accuracy = accuracy_score(y_valid, y_pred)
print(f'XGBoost Model Accuracy: {accuracy:.4f}')
print(classification_report(y_valid, y_pred))

# Predict depression status for the entire training dataset using the trained model
train_predictions = xgb_model.predict(X)

# Create a submission DataFrame with 'id' and 'depression' columns
submission_df = pd.DataFrame({
    'id': train_df['id'],  # Assuming 'id' column is present in train_df
    'depression': train_predictions  # Predicted 'depression' values
})

# Save the DataFrame to a CSV file for submission
submission_df.to_csv('submission.csv3', index=False)

print("Submission file 'submission.csv' has been created.")

XGBoost Model Accuracy: 0.9385
              precision    recall  f1-score   support

           0       0.96      0.97      0.96     22986
           1       0.84      0.82      0.83      5154

    accuracy                           0.94     28140
   macro avg       0.90      0.89      0.90     28140
weighted avg       0.94      0.94      0.94     28140

Submission file 'submission.csv' has been created.